version: '3.3'

services:
  bot:
    build: .
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data

  postgres:
    image: postgres
    restart: always
    ports:
      - "5555:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  redis_data:
  postgres_data:
