version: '3.3'

services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data: